aws:
  account_id: 838214885020
  region: ap-northeast-1
  profile: default
  env: stg
  prefix_env: example-stg

vpc:
  cidr_block: 10.0.0.0/16
  azs: [ ap-northeast-1a, ap-northeast-1c, ap-northeast-1d ]
  private_subnets: [ 10.0.1.0/24, 10.0.2.0/24, 10.0.3.0/24, 10.0.4.0/24, 10.0.5.0/24, 10.0.6.0/24 ]
  public_subnets: [ 10.0.7.0/24, 10.0.8.0/24, 10.0.9.0/24, 10.0.10.0/24, 10.0.11.0/24, 10.0.12.0/24 ]
  map_public_ip_on_launch: true
  enable_nat_gateway: false
  single_nat_gateway: false
  enable_dns_hostnames: true
  enable_flow_log: true
  create_flow_log_cloudwatch_iam_role: true
  create_flow_log_cloudwatch_log_group: true
  private_subnet_tags:
    Type: private
  public_subnet_tags:
    Type: public

ecr:
  test_repo:
    force_delete: false
    image_tag_mutability: IMMUTABLE
    scan_on_push: true
    encryption_type: KMS
    kms_key: ""

eks:
  eks_on_ec2:
    # cluster
    cluster_version: 1.26
    cluster_endpoint_private_access: true
    cluster_endpoint_public_access: true

    # self managed node group defaults
    eks_managed_node_group_defaults:
      instance_type: t3.small
      update_launch_template_default_version: true
      iam_role_additional_policies:
        AmazonSSMManagedInstanceCore: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

    # self managed node groups
    eks_managed_node_groups:
      default:
        name: default
        min_size: 3
        max_size: 3
        desired_size: 3
        pre_bootstrap_user_data: |
          echo pre_bootstrap_user_data

    # aws-auth
    aws_auth_accounts: [ ]
    aws_auth_users:
      - userarn: arn:aws:iam::838214885020:user/example-user
        username: example-user
        groups:
          - system:masters
    aws_auth_roles:
      - rolearn: arn:aws:iam::838214885020:role/example-role
        username: example-role
        groups:
          - system:masters